rreeaaddoonnllyy -- C Keyword

Storage class

rreeaaddoonnllyy  is a  C keyword  that  modifies data  declarations.  As  its name
implies, the rreeaaddoonnllyy modifier declares that data are to be read only; this
helps protect  key data against casual modification by  the user or another
programmer.

_S_e_e _A_l_s_o
CC kkeeyywwoorrddss

_N_o_t_e_s
The ANSI Standard eliminates this keyword.
