wwhhiillee -- C Keyword

Introduce a loop
wwhhiillee(_c_o_n_d_i_t_i_o_n)

wwhhiillee  is a  C keyword  that introduces a  conditional loop.   _c_o_n_d_i_t_i_o_n is
tested on reiteration  of the loop, and the loop  ends when _c_o_n_d_i_t_i_o_n is no
longer satisfied.  For example,

    while (foo < 10)

introduces a loop that will continue until the variable ffoooo is reset to ten
or greater.  Note that the statement

    while (1)

will  loop  forever,  unless  interrupted  by  a  bbrreeaakk,  ggoottoo,  or  rreettuurrnn
statement.

_S_e_e _A_l_s_o
bbrreeaakk, CC kkeeyywwoorrddss, ccoonnttiinnuuee, ddoo, ffoorr
ANSI Standard, section 6.6.5.1
