/v/fwb/doc/mwc/lx/ANSI/raise
/v/fwb/doc/mwc/lx/ANSI/rand
/v/fwb/doc/mwc/lx/TOS/random
/v/fwb/doc/mwc/lx/MULTI/randomaccess
/v/fwb/doc/mwc/lx/ANSI/rangeerror
/v/fwb/doc/mwc/lx/MULTI/ranlib
/v/fwb/doc/mwc/lx/TOS/rdy
/v/fwb/doc/mwc/lx/TOS/rdy.a
/v/fwb/doc/mwc/lx/MULTI/read
/v/fwb/doc/mwc/lx/MULTI/readonlymemory
/v/fwb/doc/mwc/lx/ANSI/realloc
/v/fwb/doc/mwc/lx/MULTI/record
/v/fwb/doc/mwc/lx/MULTI/register
/v/fwb/doc/mwc/lx/ANSI/register
/v/fwb/doc/mwc/lx/ANSI/remove
/v/fwb/doc/mwc/lx/ANSI/rename
/v/fwb/doc/mwc/lx/TOS/rescomp
/v/fwb/doc/mwc/lx/TOS/resdecom
/v/fwb/doc/mwc/lx/TOS/resource
/v/fwb/doc/mwc/lx/ANSI/return
/v/fwb/doc/mwc/lx/ANSI/rewind
/v/fwb/doc/mwc/lx/MULTI/rindex
/v/fwb/doc/mwc/lx/MULTI/rm
/v/fwb/doc/mwc/lx/MULTI/rmdir
/v/fwb/doc/mwc/lx/TOS/rsconf
/v/fwb/doc/mwc/lx/TOS/rsconf_
/v/fwb/doc/mwc/lx/MULTI/runtimestartup
/v/fwb/doc/mwc/lx/ANSI/rvalue
/v/fwb/doc/mwc/lx/TOS/rwabs
