/v/fwb/doc/mwc/lx/ANSI/fabs
/v/fwb/doc/mwc/lx/ANSI/false
/v/fwb/doc/mwc/lx/TOS/fattrib
/v/fwb/doc/mwc/lx/TOS/fclose
/v/fwb/doc/mwc/lx/ANSI/fclose
/v/fwb/doc/mwc/lx/TOS/fcreate
/v/fwb/doc/mwc/lx/MULTI/fcvt
/v/fwb/doc/mwc/lx/TOS/fdatime
/v/fwb/doc/mwc/lx/TOS/fdelete
/v/fwb/doc/mwc/lx/MULTI/fdopen
/v/fwb/doc/mwc/lx/TOS/fdup
/v/fwb/doc/mwc/lx/ANSI/feof
/v/fwb/doc/mwc/lx/ANSI/ferror
/v/fwb/doc/mwc/lx/ANSI/fflush
/v/fwb/doc/mwc/lx/TOS/fforce
/v/fwb/doc/mwc/lx/ANSI/fgetc
/v/fwb/doc/mwc/lx/TOS/fgetdta
/v/fwb/doc/mwc/lx/ANSI/fgetpos
/v/fwb/doc/mwc/lx/ANSI/fgets
/v/fwb/doc/mwc/lx/MULTI/fgetw
/v/fwb/doc/mwc/lx/MULTI/field
/v/fwb/doc/mwc/lx/MULTI/file
/v/fwb/doc/mwc/lx/ANSI/file
/v/fwb/doc/mwc/lx/ANSI/file_
/v/fwb/doc/mwc/lx/MULTI/filedescriptor
/v/fwb/doc/mwc/lx/ANSI/filename_max
/v/fwb/doc/mwc/lx/MULTI/fileno
/v/fwb/doc/mwc/lx/ANSI/float
/v/fwb/doc/mwc/lx/ANSI/float.h
/v/fwb/doc/mwc/lx/ANSI/floatingconsta
/v/fwb/doc/mwc/lx/ANSI/floor
/v/fwb/doc/mwc/lx/TOS/flopfmt
/v/fwb/doc/mwc/lx/TOS/floprd
/v/fwb/doc/mwc/lx/TOS/flopver
/v/fwb/doc/mwc/lx/TOS/flopwr
/v/fwb/doc/mwc/lx/ANSI/fmod
/v/fwb/doc/mwc/lx/ANSI/fopen
/v/fwb/doc/mwc/lx/TOS/fopen
/v/fwb/doc/mwc/lx/ANSI/for
/v/fwb/doc/mwc/lx/ANSI/fpos_t
/v/fwb/doc/mwc/lx/ANSI/fprintf
/v/fwb/doc/mwc/lx/ANSI/fputc
/v/fwb/doc/mwc/lx/ANSI/fputs
/v/fwb/doc/mwc/lx/MULTI/fputw
/v/fwb/doc/mwc/lx/ANSI/fread
/v/fwb/doc/mwc/lx/TOS/fread
/v/fwb/doc/mwc/lx/ANSI/free
/v/fwb/doc/mwc/lx/TOS/frename
/v/fwb/doc/mwc/lx/ANSI/freopen
/v/fwb/doc/mwc/lx/ANSI/frexp
/v/fwb/doc/mwc/lx/ANSI/fscanf
/v/fwb/doc/mwc/lx/ANSI/fseek
/v/fwb/doc/mwc/lx/TOS/fseek
/v/fwb/doc/mwc/lx/TOS/fsetdta
/v/fwb/doc/mwc/lx/ANSI/fsetpos
/v/fwb/doc/mwc/lx/TOS/fsfirst
/v/fwb/doc/mwc/lx/TOS/fsnext
/v/fwb/doc/mwc/lx/MULTI/fstat
/v/fwb/doc/mwc/lx/ANSI/ftell
/v/fwb/doc/mwc/lx/ANSI/function
/v/fwb/doc/mwc/lx/ANSI/functioncall
/v/fwb/doc/mwc/lx/ANSI/functiondeclar
/v/fwb/doc/mwc/lx/ANSI/functiondefini
/v/fwb/doc/mwc/lx/ANSI/functiondesign
/v/fwb/doc/mwc/lx/ANSI/functionprotot
/v/fwb/doc/mwc/lx/ANSI/fwrite
/v/fwb/doc/mwc/lx/TOS/fwrite
