/v/fwb/doc/mwc/lx/ANSI/parameter
/v/fwb/doc/mwc/lx/MULTI/path
/v/fwb/doc/mwc/lx/MULTI/path.a
/v/fwb/doc/mwc/lx/MULTI/path.h
/v/fwb/doc/mwc/lx/MULTI/pattern
/v/fwb/doc/mwc/lx/MULTI/peekb
/v/fwb/doc/mwc/lx/TOS/peekl
/v/fwb/doc/mwc/lx/TOS/peekw
/v/fwb/doc/mwc/lx/ANSI/perror
/v/fwb/doc/mwc/lx/TOS/pexec
/v/fwb/doc/mwc/lx/TOS/physbase
/v/fwb/doc/mwc/lx/MULTI/picture
/v/fwb/doc/mwc/lx/MULTI/pnmatch
/v/fwb/doc/mwc/lx/ANSI/pointer
/v/fwb/doc/mwc/lx/ANSI/pointerdeclara
/v/fwb/doc/mwc/lx/TOS/pokeb
/v/fwb/doc/mwc/lx/TOS/pokel
/v/fwb/doc/mwc/lx/TOS/pokew
/v/fwb/doc/mwc/lx/MULTI/port
/v/fwb/doc/mwc/lx/ANSI/portability
/v/fwb/doc/mwc/lx/ANSI/pow
/v/fwb/doc/mwc/lx/MULTI/pr
/v/fwb/doc/mwc/lx/ANSI/preprocessing
/v/fwb/doc/mwc/lx/ANSI/preprocessingn
/v/fwb/doc/mwc/lx/ANSI/printf
/v/fwb/doc/mwc/lx/MULTI/prn
/v/fwb/doc/mwc/lx/MULTI/process
/v/fwb/doc/mwc/lx/ANSI/programstartup
/v/fwb/doc/mwc/lx/ANSI/programtermina
/v/fwb/doc/mwc/lx/TOS/protobt
/v/fwb/doc/mwc/lx/TOS/prtblk
/v/fwb/doc/mwc/lx/TOS/pterm
/v/fwb/doc/mwc/lx/TOS/pterm0
/v/fwb/doc/mwc/lx/TOS/ptermres
/v/fwb/doc/mwc/lx/ANSI/ptrdiff_t
/v/fwb/doc/mwc/lx/MULTI/pun
/v/fwb/doc/mwc/lx/ANSI/punctuators
/v/fwb/doc/mwc/lx/TOS/puntaes
/v/fwb/doc/mwc/lx/ANSI/putc
/v/fwb/doc/mwc/lx/ANSI/putchar
/v/fwb/doc/mwc/lx/ANSI/puts
/v/fwb/doc/mwc/lx/MULTI/putw
/v/fwb/doc/mwc/lx/MULTI/pwd
