#!/bin/sh
#
# Compile the release notes for the COHERENT system
#
TROFF="troff -p -Z6 -rRN1 -rNS1 -rNI1"
OUTPUT=/tmp/doc/rel.notes
V=/v/doc/coherent/manual

rm $OUTPUT/*

$TROFF -mcohtext $V/fonts.r $V/top.r \
	changes.r \
	2>notes.x > $OUTPUT/changes.4210.p
