/v/doc/coherent/lx/raise
/v/doc/coherent/lx/ram
/v/doc/coherent/lx/ramdisk
/v/doc/coherent/lx/rand
/v/doc/coherent/lx/rand_max
/v/doc/coherent/lx/random
/v/doc/coherent/lx/random_ac
/v/doc/coherent/lx/ranlib
/v/doc/coherent/lx/rc
/v/doc/coherent/lx/read-only
/v/doc/coherent/lx/read.c
/v/doc/coherent/lx/read.s
/v/doc/coherent/lx/readdir
/v/doc/coherent/lx/readline
/v/doc/coherent/lx/readonlyc
/v/doc/coherent/lx/readonlyk
/v/doc/coherent/lx/realloc
/v/doc/coherent/lx/reboot
/v/doc/coherent/lx/recursion
/v/doc/coherent/lx/recv
/v/doc/coherent/lx/recvfrom
/v/doc/coherent/lx/ref
/v/doc/coherent/lx/regcomp
/v/doc/coherent/lx/regerror
/v/doc/coherent/lx/regexec
/v/doc/coherent/lx/regexp.h
/v/doc/coherent/lx/register
/v/doc/coherent/lx/registerv
/v/doc/coherent/lx/regsub
/v/doc/coherent/lx/remove
/v/doc/coherent/lx/rename
/v/doc/coherent/lx/reprint
/v/doc/coherent/lx/resetterm
/v/doc/coherent/lx/restor
/v/doc/coherent/lx/return
/v/doc/coherent/lx/rev
/v/doc/coherent/lx/rewind
/v/doc/coherent/lx/rewinddir
/v/doc/coherent/lx/rindex
/v/doc/coherent/lx/rm
/v/doc/coherent/lx/rmail
/v/doc/coherent/lx/rmdir.c
/v/doc/coherent/lx/rmdir.s
/v/doc/coherent/lx/root
/v/doc/coherent/lx/route
/v/doc/coherent/lx/routers
/v/doc/coherent/lx/rpow
/v/doc/coherent/lx/rs-232
/v/doc/coherent/lx/rsmtp
/v/doc/coherent/lx/rubik
/v/doc/coherent/lx/runq
/v/doc/coherent/lx/rvalue
