/*
**	term.h -- Definition of struct term
**	Automatically generated - Do not hand-modify!
*/

#ifndef	__TERM_H__
#define	__TERM_H__

#include <common/feature.h>
#include <common/ccompat.h>

#if	_POSIX_C_SOURCE || _STDC_SOURCE
# define	__TERM(member)	__CONCAT (_, member)
#else
# define	__TERM(member)	member
# define	_first_term	__first_term
# define	cur_term	__cur_term
# define	CUR		__CUR
#endif

#ifndef SGTTY
# include <curses.h>
# include <termio.h>
#endif

#ifdef SINGLE
#	define __CUR __first_term.
#else
#	define __CUR __cur_term->
#endif


#define auto_left_margin               __CUR __TERM (Booleans) [0]
#define auto_right_margin              __CUR __TERM (Booleans) [1]
#define no_esc_ctlc                    __CUR __TERM (Booleans) [2]
#define ceol_standout_glitch           __CUR __TERM (Booleans) [3]
#define eat_newline_glitch             __CUR __TERM (Booleans) [4]
#define erase_overstrike               __CUR __TERM (Booleans) [5]
#define generic_type                   __CUR __TERM (Booleans) [6]
#define hard_copy                      __CUR __TERM (Booleans) [7]
#define has_meta_key                   __CUR __TERM (Booleans) [8]
#define has_status_line                __CUR __TERM (Booleans) [9]
#define insert_null_glitch             __CUR __TERM (Booleans) [10]
#define memory_above                   __CUR __TERM (Booleans) [11]
#define memory_below                   __CUR __TERM (Booleans) [12]
#define move_insert_mode               __CUR __TERM (Booleans) [13]
#define move_standout_mode             __CUR __TERM (Booleans) [14]
#define over_strike                    __CUR __TERM (Booleans) [15]
#define status_line_esc_ok             __CUR __TERM (Booleans) [16]
#define dest_tabs_magic_smso           __CUR __TERM (Booleans) [17]
#define tilde_glitch                   __CUR __TERM (Booleans) [18]
#define transparent_underline          __CUR __TERM (Booleans) [19]
#define xon_xoff                       __CUR __TERM (Booleans) [20]
#define needs_xon_xoff                 __CUR __TERM (Booleans) [21]
#define prtr_silent                    __CUR __TERM (Booleans) [22]
#define hard_cursor                    __CUR __TERM (Booleans) [23]
#define non_rev_rmcup                  __CUR __TERM (Booleans) [24]
#define no_pad_char                    __CUR __TERM (Booleans) [25]
#define non_dest_scroll_region         __CUR __TERM (Booleans) [26]
#define can_change                     __CUR __TERM (Booleans) [27]
#define back_color_erase               __CUR __TERM (Booleans) [28]
#define hue_lightness_saturation       __CUR __TERM (Booleans) [29]
#define col_addr_glitch                __CUR __TERM (Booleans) [30]
#define cr_cancels_micro_mode          __CUR __TERM (Booleans) [31]
#define has_print_wheel                __CUR __TERM (Booleans) [32]
#define row_addr_glitch                __CUR __TERM (Booleans) [33]
#define semi_auto_right_margin         __CUR __TERM (Booleans) [34]
#define cpi_changes_res                __CUR __TERM (Booleans) [35]
#define lpi_changes_res                __CUR __TERM (Booleans) [36]
#define columns                        __CUR __TERM (Numbers) [0]
#define init_tabs                      __CUR __TERM (Numbers) [1]
#define lines                          __CUR __TERM (Numbers) [2]
#define lines_of_memory                __CUR __TERM (Numbers) [3]
#define magic_cookie_glitch            __CUR __TERM (Numbers) [4]
#define padding_baud_rate              __CUR __TERM (Numbers) [5]
#define virtual_terminal               __CUR __TERM (Numbers) [6]
#define width_status_line              __CUR __TERM (Numbers) [7]
#define num_labels                     __CUR __TERM (Numbers) [8]
#define label_height                   __CUR __TERM (Numbers) [9]
#define label_width                    __CUR __TERM (Numbers) [10]
#define max_attributes                 __CUR __TERM (Numbers) [11]
#define maximum_windows                __CUR __TERM (Numbers) [12]
#define max_colors                     __CUR __TERM (Numbers) [13]
#define max_pairs                      __CUR __TERM (Numbers) [14]
#define no_color_video                 __CUR __TERM (Numbers) [15]
#define buffer_capacity                __CUR __TERM (Numbers) [16]
#define dot_vert_spacing               __CUR __TERM (Numbers) [17]
#define dot_horz_spacing               __CUR __TERM (Numbers) [18]
#define max_micro_address              __CUR __TERM (Numbers) [19]
#define max_micro_jump                 __CUR __TERM (Numbers) [20]
#define micro_char_size                __CUR __TERM (Numbers) [21]
#define micro_line_size                __CUR __TERM (Numbers) [22]
#define number_of_pins                 __CUR __TERM (Numbers) [23]
#define output_res_char                __CUR __TERM (Numbers) [24]
#define output_res_line                __CUR __TERM (Numbers) [25]
#define output_res_horz                __CUR __TERM (Numbers) [26]
#define output_res_vert                __CUR __TERM (Numbers) [27]
#define print_rate                     __CUR __TERM (Numbers) [28]
#define wide_char_size                 __CUR __TERM (Numbers) [29]
#define back_tab                       __CUR __TERM (Strings) [0]
#define bell                           __CUR __TERM (Strings) [1]
#define carriage_return                __CUR __TERM (Strings) [2]
#define change_scroll_region           __CUR __TERM (Strings) [3]
#define clear_all_tabs                 __CUR __TERM (Strings) [4]
#define clear_screen                   __CUR __TERM (Strings) [5]
#define clr_eol                        __CUR __TERM (Strings) [6]
#define clr_eos                        __CUR __TERM (Strings) [7]
#define column_address                 __CUR __TERM (Strings) [8]
#define command_character              __CUR __TERM (Strings) [9]
#define cursor_address                 __CUR __TERM (Strings) [10]
#define cursor_down                    __CUR __TERM (Strings) [11]
#define cursor_home                    __CUR __TERM (Strings) [12]
#define cursor_invisible               __CUR __TERM (Strings) [13]
#define cursor_left                    __CUR __TERM (Strings) [14]
#define cursor_mem_address             __CUR __TERM (Strings) [15]
#define cursor_normal                  __CUR __TERM (Strings) [16]
#define cursor_right                   __CUR __TERM (Strings) [17]
#define cursor_to_ll                   __CUR __TERM (Strings) [18]
#define cursor_up                      __CUR __TERM (Strings) [19]
#define cursor_visible                 __CUR __TERM (Strings) [20]
#define delete_character               __CUR __TERM (Strings) [21]
#define delete_line                    __CUR __TERM (Strings) [22]
#define dis_status_line                __CUR __TERM (Strings) [23]
#define down_half_line                 __CUR __TERM (Strings) [24]
#define enter_alt_charset_mode         __CUR __TERM (Strings) [25]
#define enter_blink_mode               __CUR __TERM (Strings) [26]
#define enter_bold_mode                __CUR __TERM (Strings) [27]
#define enter_ca_mode                  __CUR __TERM (Strings) [28]
#define enter_delete_mode              __CUR __TERM (Strings) [29]
#define enter_dim_mode                 __CUR __TERM (Strings) [30]
#define enter_insert_mode              __CUR __TERM (Strings) [31]
#define enter_secure_mode              __CUR __TERM (Strings) [32]
#define enter_protected_mode           __CUR __TERM (Strings) [33]
#define enter_reverse_mode             __CUR __TERM (Strings) [34]
#define enter_standout_mode            __CUR __TERM (Strings) [35]
#define enter_underline_mode           __CUR __TERM (Strings) [36]
#define erase_chars                    __CUR __TERM (Strings) [37]
#define exit_alt_charset_mode          __CUR __TERM (Strings) [38]
#define exit_attribute_mode            __CUR __TERM (Strings) [39]
#define exit_ca_mode                   __CUR __TERM (Strings) [40]
#define exit_delete_mode               __CUR __TERM (Strings) [41]
#define exit_insert_mode               __CUR __TERM (Strings) [42]
#define exit_standout_mode             __CUR __TERM (Strings) [43]
#define exit_underline_mode            __CUR __TERM (Strings) [44]
#define flash_screen                   __CUR __TERM (Strings) [45]
#define form_feed                      __CUR __TERM (Strings) [46]
#define from_status_line               __CUR __TERM (Strings) [47]
#define init_1string                   __CUR __TERM (Strings) [48]
#define init_2string                   __CUR __TERM (Strings) [49]
#define init_3string                   __CUR __TERM (Strings) [50]
#define init_file                      __CUR __TERM (Strings) [51]
#define insert_character               __CUR __TERM (Strings) [52]
#define insert_line                    __CUR __TERM (Strings) [53]
#define insert_padding                 __CUR __TERM (Strings) [54]
#define key_backspace                  __CUR __TERM (Strings) [55]
#define key_catab                      __CUR __TERM (Strings) [56]
#define key_clear                      __CUR __TERM (Strings) [57]
#define key_ctab                       __CUR __TERM (Strings) [58]
#define key_dc                         __CUR __TERM (Strings) [59]
#define key_dl                         __CUR __TERM (Strings) [60]
#define key_down                       __CUR __TERM (Strings) [61]
#define key_eic                        __CUR __TERM (Strings) [62]
#define key_eol                        __CUR __TERM (Strings) [63]
#define key_eos                        __CUR __TERM (Strings) [64]
#define key_f0                         __CUR __TERM (Strings) [65]
#define key_f1                         __CUR __TERM (Strings) [66]
#define key_f10                        __CUR __TERM (Strings) [67]
#define key_f2                         __CUR __TERM (Strings) [68]
#define key_f3                         __CUR __TERM (Strings) [69]
#define key_f4                         __CUR __TERM (Strings) [70]
#define key_f5                         __CUR __TERM (Strings) [71]
#define key_f6                         __CUR __TERM (Strings) [72]
#define key_f7                         __CUR __TERM (Strings) [73]
#define key_f8                         __CUR __TERM (Strings) [74]
#define key_f9                         __CUR __TERM (Strings) [75]
#define key_home                       __CUR __TERM (Strings) [76]
#define key_ic                         __CUR __TERM (Strings) [77]
#define key_il                         __CUR __TERM (Strings) [78]
#define key_left                       __CUR __TERM (Strings) [79]
#define key_ll                         __CUR __TERM (Strings) [80]
#define key_npage                      __CUR __TERM (Strings) [81]
#define key_ppage                      __CUR __TERM (Strings) [82]
#define key_right                      __CUR __TERM (Strings) [83]
#define key_sf                         __CUR __TERM (Strings) [84]
#define key_sr                         __CUR __TERM (Strings) [85]
#define key_stab                       __CUR __TERM (Strings) [86]
#define key_up                         __CUR __TERM (Strings) [87]
#define keypad_local                   __CUR __TERM (Strings) [88]
#define keypad_xmit                    __CUR __TERM (Strings) [89]
#define lab_f0                         __CUR __TERM (Strings) [90]
#define lab_f1                         __CUR __TERM (Strings) [91]
#define lab_f10                        __CUR __TERM (Strings) [92]
#define lab_f2                         __CUR __TERM (Strings) [93]
#define lab_f3                         __CUR __TERM (Strings) [94]
#define lab_f4                         __CUR __TERM (Strings) [95]
#define lab_f5                         __CUR __TERM (Strings) [96]
#define lab_f6                         __CUR __TERM (Strings) [97]
#define lab_f7                         __CUR __TERM (Strings) [98]
#define lab_f8                         __CUR __TERM (Strings) [99]
#define lab_f9                         __CUR __TERM (Strings) [100]
#define meta_off                       __CUR __TERM (Strings) [101]
#define meta_on                        __CUR __TERM (Strings) [102]
#define newline                        __CUR __TERM (Strings) [103]
#define pad_char                       __CUR __TERM (Strings) [104]
#define parm_dch                       __CUR __TERM (Strings) [105]
#define parm_delete_line               __CUR __TERM (Strings) [106]
#define parm_down_cursor               __CUR __TERM (Strings) [107]
#define parm_ich                       __CUR __TERM (Strings) [108]
#define parm_index                     __CUR __TERM (Strings) [109]
#define parm_insert_line               __CUR __TERM (Strings) [110]
#define parm_left_cursor               __CUR __TERM (Strings) [111]
#define parm_right_cursor              __CUR __TERM (Strings) [112]
#define parm_rindex                    __CUR __TERM (Strings) [113]
#define parm_up_cursor                 __CUR __TERM (Strings) [114]
#define pkey_key                       __CUR __TERM (Strings) [115]
#define pkey_local                     __CUR __TERM (Strings) [116]
#define pkey_xmit                      __CUR __TERM (Strings) [117]
#define print_screen                   __CUR __TERM (Strings) [118]
#define prtr_off                       __CUR __TERM (Strings) [119]
#define prtr_on                        __CUR __TERM (Strings) [120]
#define repeat_char                    __CUR __TERM (Strings) [121]
#define reset_1string                  __CUR __TERM (Strings) [122]
#define reset_2string                  __CUR __TERM (Strings) [123]
#define reset_3string                  __CUR __TERM (Strings) [124]
#define reset_file                     __CUR __TERM (Strings) [125]
#define restore_cursor                 __CUR __TERM (Strings) [126]
#define row_address                    __CUR __TERM (Strings) [127]
#define save_cursor                    __CUR __TERM (Strings) [128]
#define scroll_forward                 __CUR __TERM (Strings) [129]
#define scroll_reverse                 __CUR __TERM (Strings) [130]
#define set_attributes                 __CUR __TERM (Strings) [131]
#define set_tab                        __CUR __TERM (Strings) [132]
#define set_window                     __CUR __TERM (Strings) [133]
#define tab                            __CUR __TERM (Strings) [134]
#define to_status_line                 __CUR __TERM (Strings) [135]
#define underline_char                 __CUR __TERM (Strings) [136]
#define up_half_line                   __CUR __TERM (Strings) [137]
#define init_prog                      __CUR __TERM (Strings) [138]
#define key_a1                         __CUR __TERM (Strings) [139]
#define key_a3                         __CUR __TERM (Strings) [140]
#define key_b2                         __CUR __TERM (Strings) [141]
#define key_c1                         __CUR __TERM (Strings) [142]
#define key_c3                         __CUR __TERM (Strings) [143]
#define prtr_non                       __CUR __TERM (Strings) [144]
#define char_padding                   __CUR __TERM (Strings) [145]
#define acs_chars                      __CUR __TERM (Strings) [146]
#define plab_norm                      __CUR __TERM (Strings) [147]
#define key_btab                       __CUR __TERM (Strings) [148]
#define enter_xon_mode                 __CUR __TERM (Strings) [149]
#define exit_xon_mode                  __CUR __TERM (Strings) [150]
#define enter_am_mode                  __CUR __TERM (Strings) [151]
#define exit_am_mode                   __CUR __TERM (Strings) [152]
#define xon_character                  __CUR __TERM (Strings) [153]
#define xoff_character                 __CUR __TERM (Strings) [154]
#define ena_acs                        __CUR __TERM (Strings) [155]
#define label_on                       __CUR __TERM (Strings) [156]
#define label_off                      __CUR __TERM (Strings) [157]
#define key_beg                        __CUR __TERM (Strings) [158]
#define key_cancel                     __CUR __TERM (Strings) [159]
#define key_close                      __CUR __TERM (Strings) [160]
#define key_command                    __CUR __TERM (Strings) [161]
#define key_copy                       __CUR __TERM (Strings) [162]
#define key_create                     __CUR __TERM (Strings) [163]
#define key_end                        __CUR __TERM (Strings) [164]
#define key_enter                      __CUR __TERM (Strings) [165]
#define key_exit                       __CUR __TERM (Strings) [166]
#define key_find                       __CUR __TERM (Strings) [167]
#define key_help                       __CUR __TERM (Strings) [168]
#define key_mark                       __CUR __TERM (Strings) [169]
#define key_message                    __CUR __TERM (Strings) [170]
#define key_move                       __CUR __TERM (Strings) [171]
#define key_next                       __CUR __TERM (Strings) [172]
#define key_open                       __CUR __TERM (Strings) [173]
#define key_options                    __CUR __TERM (Strings) [174]
#define key_previous                   __CUR __TERM (Strings) [175]
#define key_print                      __CUR __TERM (Strings) [176]
#define key_redo                       __CUR __TERM (Strings) [177]
#define key_reference                  __CUR __TERM (Strings) [178]
#define key_refresh                    __CUR __TERM (Strings) [179]
#define key_replace                    __CUR __TERM (Strings) [180]
#define key_restart                    __CUR __TERM (Strings) [181]
#define key_resume                     __CUR __TERM (Strings) [182]
#define key_save                       __CUR __TERM (Strings) [183]
#define key_suspend                    __CUR __TERM (Strings) [184]
#define key_undo                       __CUR __TERM (Strings) [185]
#define key_sbeg                       __CUR __TERM (Strings) [186]
#define key_scancel                    __CUR __TERM (Strings) [187]
#define key_scommand                   __CUR __TERM (Strings) [188]
#define key_scopy                      __CUR __TERM (Strings) [189]
#define key_screate                    __CUR __TERM (Strings) [190]
#define key_sdc                        __CUR __TERM (Strings) [191]
#define key_sdl                        __CUR __TERM (Strings) [192]
#define key_select                     __CUR __TERM (Strings) [193]
#define key_send                       __CUR __TERM (Strings) [194]
#define key_seol                       __CUR __TERM (Strings) [195]
#define key_sexit                      __CUR __TERM (Strings) [196]
#define key_sfind                      __CUR __TERM (Strings) [197]
#define key_shelp                      __CUR __TERM (Strings) [198]
#define key_shome                      __CUR __TERM (Strings) [199]
#define key_sic                        __CUR __TERM (Strings) [200]
#define key_sleft                      __CUR __TERM (Strings) [201]
#define key_smessage                   __CUR __TERM (Strings) [202]
#define key_smove                      __CUR __TERM (Strings) [203]
#define key_snext                      __CUR __TERM (Strings) [204]
#define key_soptions                   __CUR __TERM (Strings) [205]
#define key_sprevious                  __CUR __TERM (Strings) [206]
#define key_sprint                     __CUR __TERM (Strings) [207]
#define key_sredo                      __CUR __TERM (Strings) [208]
#define key_sreplace                   __CUR __TERM (Strings) [209]
#define key_sright                     __CUR __TERM (Strings) [210]
#define key_srsume                     __CUR __TERM (Strings) [211]
#define key_ssave                      __CUR __TERM (Strings) [212]
#define key_ssuspend                   __CUR __TERM (Strings) [213]
#define key_sundo                      __CUR __TERM (Strings) [214]
#define req_for_input                  __CUR __TERM (Strings) [215]
#define key_f11                        __CUR __TERM (Strings) [216]
#define key_f12                        __CUR __TERM (Strings) [217]
#define key_f13                        __CUR __TERM (Strings) [218]
#define key_f14                        __CUR __TERM (Strings) [219]
#define key_f15                        __CUR __TERM (Strings) [220]
#define key_f16                        __CUR __TERM (Strings) [221]
#define key_f17                        __CUR __TERM (Strings) [222]
#define key_f18                        __CUR __TERM (Strings) [223]
#define key_f19                        __CUR __TERM (Strings) [224]
#define key_f20                        __CUR __TERM (Strings) [225]
#define key_f21                        __CUR __TERM (Strings) [226]
#define key_f22                        __CUR __TERM (Strings) [227]
#define key_f23                        __CUR __TERM (Strings) [228]
#define key_f24                        __CUR __TERM (Strings) [229]
#define key_f25                        __CUR __TERM (Strings) [230]
#define key_f26                        __CUR __TERM (Strings) [231]
#define key_f27                        __CUR __TERM (Strings) [232]
#define key_f28                        __CUR __TERM (Strings) [233]
#define key_f29                        __CUR __TERM (Strings) [234]
#define key_f30                        __CUR __TERM (Strings) [235]
#define key_f31                        __CUR __TERM (Strings) [236]
#define key_f32                        __CUR __TERM (Strings) [237]
#define key_f33                        __CUR __TERM (Strings) [238]
#define key_f34                        __CUR __TERM (Strings) [239]
#define key_f35                        __CUR __TERM (Strings) [240]
#define key_f36                        __CUR __TERM (Strings) [241]
#define key_f37                        __CUR __TERM (Strings) [242]
#define key_f38                        __CUR __TERM (Strings) [243]
#define key_f39                        __CUR __TERM (Strings) [244]
#define key_f40                        __CUR __TERM (Strings) [245]
#define key_f41                        __CUR __TERM (Strings) [246]
#define key_f42                        __CUR __TERM (Strings) [247]
#define key_f43                        __CUR __TERM (Strings) [248]
#define key_f44                        __CUR __TERM (Strings) [249]
#define key_f45                        __CUR __TERM (Strings) [250]
#define key_f46                        __CUR __TERM (Strings) [251]
#define key_f47                        __CUR __TERM (Strings) [252]
#define key_f48                        __CUR __TERM (Strings) [253]
#define key_f49                        __CUR __TERM (Strings) [254]
#define key_f50                        __CUR __TERM (Strings) [255]
#define key_f51                        __CUR __TERM (Strings) [256]
#define key_f52                        __CUR __TERM (Strings) [257]
#define key_f53                        __CUR __TERM (Strings) [258]
#define key_f54                        __CUR __TERM (Strings) [259]
#define key_f55                        __CUR __TERM (Strings) [260]
#define key_f56                        __CUR __TERM (Strings) [261]
#define key_f57                        __CUR __TERM (Strings) [262]
#define key_f58                        __CUR __TERM (Strings) [263]
#define key_f59                        __CUR __TERM (Strings) [264]
#define key_f60                        __CUR __TERM (Strings) [265]
#define key_f61                        __CUR __TERM (Strings) [266]
#define key_f62                        __CUR __TERM (Strings) [267]
#define key_f63                        __CUR __TERM (Strings) [268]
#define clr_bol                        __CUR __TERM (Strings) [269]
#define clear_margins                  __CUR __TERM (Strings) [270]
#define set_left_margin                __CUR __TERM (Strings) [271]
#define set_right_margin               __CUR __TERM (Strings) [272]
#define label_format                   __CUR __TERM (Strings) [273]
#define set_clock                      __CUR __TERM (Strings) [274]
#define display_clock                  __CUR __TERM (Strings) [275]
#define remove_clock                   __CUR __TERM (Strings) [276]
#define create_window                  __CUR __TERM (Strings) [277]
#define goto_window                    __CUR __TERM (Strings) [278]
#define hangup                         __CUR __TERM (Strings) [279]
#define dial_phone                     __CUR __TERM (Strings) [280]
#define quick_dial                     __CUR __TERM (Strings) [281]
#define tone                           __CUR __TERM (Strings) [282]
#define pulse                          __CUR __TERM (Strings) [283]
#define flash_hook                     __CUR __TERM (Strings) [284]
#define fixed_pause                    __CUR __TERM (Strings) [285]
#define wait_tone                      __CUR __TERM (Strings) [286]
#define user0                          __CUR __TERM (Strings) [287]
#define user1                          __CUR __TERM (Strings) [288]
#define user2                          __CUR __TERM (Strings) [289]
#define user3                          __CUR __TERM (Strings) [290]
#define user4                          __CUR __TERM (Strings) [291]
#define user5                          __CUR __TERM (Strings) [292]
#define user6                          __CUR __TERM (Strings) [293]
#define user7                          __CUR __TERM (Strings) [294]
#define user8                          __CUR __TERM (Strings) [295]
#define user9                          __CUR __TERM (Strings) [296]
#define orig_pair                      __CUR __TERM (Strings) [297]
#define orig_colors                    __CUR __TERM (Strings) [298]
#define initialize_color               __CUR __TERM (Strings) [299]
#define initialize_pair                __CUR __TERM (Strings) [300]
#define set_color_pair                 __CUR __TERM (Strings) [301]
#define set_foreground                 __CUR __TERM (Strings) [302]
#define set_background                 __CUR __TERM (Strings) [303]
#define change_char_pitch              __CUR __TERM (Strings) [304]
#define change_line_pitch              __CUR __TERM (Strings) [305]
#define change_res_horz                __CUR __TERM (Strings) [306]
#define change_res_vert                __CUR __TERM (Strings) [307]
#define define_char                    __CUR __TERM (Strings) [308]
#define enter_doublewide_mode          __CUR __TERM (Strings) [309]
#define enter_draft_quality            __CUR __TERM (Strings) [310]
#define enter_italics_mode             __CUR __TERM (Strings) [311]
#define enter_leftward_mode            __CUR __TERM (Strings) [312]
#define enter_micro_mode               __CUR __TERM (Strings) [313]
#define enter_nr_letter_quality        __CUR __TERM (Strings) [314]
#define enter_normal_quality           __CUR __TERM (Strings) [315]
#define enter_shadow_mode              __CUR __TERM (Strings) [316]
#define enter_subscript_mode           __CUR __TERM (Strings) [317]
#define enter_superscript_mode         __CUR __TERM (Strings) [318]
#define enter_upward_mode              __CUR __TERM (Strings) [319]
#define exit_doublewide_mode           __CUR __TERM (Strings) [320]
#define exit_italics_mode              __CUR __TERM (Strings) [321]
#define exit_leftward_mode             __CUR __TERM (Strings) [322]
#define exit_micro_mode                __CUR __TERM (Strings) [323]
#define exit_shadow_mode               __CUR __TERM (Strings) [324]
#define exit_subscript_mode            __CUR __TERM (Strings) [325]
#define exit_superscript_mode          __CUR __TERM (Strings) [326]
#define exit_upward_mode               __CUR __TERM (Strings) [327]
#define micro_column_address           __CUR __TERM (Strings) [328]
#define micro_down                     __CUR __TERM (Strings) [329]
#define micro_left                     __CUR __TERM (Strings) [330]
#define micro_right                    __CUR __TERM (Strings) [331]
#define micro_row_address              __CUR __TERM (Strings) [332]
#define micro_up                       __CUR __TERM (Strings) [333]
#define order_of_pins                  __CUR __TERM (Strings) [334]
#define parm_down_micro                __CUR __TERM (Strings) [335]
#define parm_left_micro                __CUR __TERM (Strings) [336]
#define parm_right_micro               __CUR __TERM (Strings) [337]
#define parm_up_micro                  __CUR __TERM (Strings) [338]
#define select_char_set                __CUR __TERM (Strings) [339]
#define set_bottom_margin              __CUR __TERM (Strings) [340]
#define set_bottom_margin_parm         __CUR __TERM (Strings) [341]
#define set_left_margin_parm           __CUR __TERM (Strings) [342]
#define set_right_margin_parm          __CUR __TERM (Strings) [343]
#define set_top_margin                 __CUR __TERM (Strings) [344]
#define set_top_margin_parm            __CUR __TERM (Strings) [345]
#define start_bit_image                __CUR __TERM (Strings) [346]
#define start_char_set_def             __CUR __TERM (Strings) [347]
#define stop_bit_image                 __CUR __TERM (Strings) [348]
#define stop_char_set_def              __CUR __TERM (Strings) [349]
#define subscript_characters           __CUR __TERM (Strings) [350]
#define superscript_characters         __CUR __TERM (Strings) [351]
#define these_cause_cr                 __CUR __TERM (Strings) [352]
#define zero_motion                    __CUR __TERM (Strings) [353]
#define char_set_names                 __CUR __TERM (Strings) [354]


struct term {
	char	      *	__TERM (term_names);	/* offset in str_table of
						 * terminal names */
	char	      *	__TERM (str_table);	/* pointer to string table */
	short		__TERM (Filedes);	/* file description being
						 * written to */
#ifdef USE_TERMIO
	struct termio	__TERM (Otermio);
	struct termio	__TERM (Ntermio);
#else
	SGTTY		__TERM (Ottyb);		/* old terminal state */
	SGTTY		__TERM (Nttyb);		/* current terminal state */
#endif

	char		__TERM (Booleans) [37];
	short		__TERM (Numbers) [30];
	char	      *	__TERM (Strings) [355];
};

extern	struct term	__first_term;
extern	struct term   *	__cur_term;

#if	! _POSIX_C_SOURCE && ! _STDC_SOURCE
# define	BOOLCOUNT 37
# define	NUMCOUNT  30
# define	STRCOUNT  355
#endif

#endif	/* ! defined (__TERM_H__) */
