#!/bin/sh

OUTPUT=/tmp/doc/rel.notes
TROFF="troff -p"

rm $OUTPUT/*

$TROFF /v/doc/coherent/fonts.r /v/doc/coherent/top.r title.r > $OUTPUT/title.p
$TROFF /v/doc/coherent/fonts.r /v/doc/coherent/top.r copyright.r > $OUTPUT/copyright.p
$TROFF -mcohtext /v/doc/coherent/fonts.r /v/doc/coherent/top.r intro.r 2> gnu.x > $OUTPUT/intro.p
