iiff -- C Keyword

Introduce a conditional statement

iiff is a C keyword that introduces a conditional statement.  For example,

    if (i==10)
        dosomething();

will ddoossoommeetthhiinngg only if ii equals ten.

iiff statements can be used with  the statements eellssee iiff and eellssee to create a
chain of  conditional statements.  Such  a chain can include  any number of
eellssee iiff statements, but only one eellssee statement.

_S_e_e _A_l_s_o
CC kkeeyywwoorrddss, eellssee
ANSI Standard, section 6.6.4.1
